name: Grunt build and commit

on: [push]

jobs:
  grunt-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Compile with Grunt
        uses: elstudio/actions-js-build/build@v4
        with:
          args: run-script release

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        with:
          commit_message: Apply changes to release
