name: Grunt build and commit

on: [push]

jobs:
  grunt-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile with Grunt
        uses: elstudio/actions-js-build/build@v2
        with:
          args: run-script release

#      - name: Commit changes
#        uses: elstudio/actions-js-build/commit@v3
